@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <chart-component class="my-4"></chart-component>
            <h3>Project Description</h3>
            <p>Remote Control System is a platform used for analyzing and displaying readings in real time using API and Websocket.</p>

            <h3 class="mt-4">Technologies Used</h3>
            <p><a href="https://pusher.com/" target="_blank">Pusher</a></p>
            <p><a href="https://laravel.com/docs/8.x/broadcasting" target="_blank">Laravel Broadcasting feature</a></p>
            <p><a href="https://laravel.com/docs/8.x/broadcasting#client-pusher-channels" target="_blank">Laravel Echo</a></p>
            <p><a href="https://vuejs.org/" target="_blank">VueJS</a></p>
        </div>

        <div class="col-lg-4">
            <h3>How it works?</h3>
            <p>Readings are typically generated by sensors and sent via HTTP requests by a microcontroller.</p>
            <p>The application receives the HTTP request sent by the microcontroller and stores in after processing.</p>
            <p>On storing data, an event is triggered; updating data in real time for all listeners on the websocket channel.</p>
            <p>The dashboard containing the readings from sensors is updated in real time using VueJS.</p>
        </div>
    </div>
</div>
@endsection
